# Generated by Django 3.1 on 2021-12-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_artist',
            field=models.ManyToManyField(to='store.Artist'),
        ),
    ]
