# Generated by Django 3.2.12 on 2022-02-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220131_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.ImageField(upload_to='C:\\Users\\William YAO\\Desktop\\LE BATEAU PIRATE\\disquaire_project\\disquaire_project\\..\\img'),
        ),
    ]
