# Generated by Django 3.2.12 on 2022-03-08 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220308_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.album'),
        ),
    ]
