# Generated by Django 3.2.12 on 2022-03-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_booking_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='commande',
        ),
        migrations.AddField(
            model_name='booking',
            name='pre_commande',
            field=models.BooleanField(default=False),
        ),
    ]
